"""The published ``coordinode`` package must allow only runtimes its generated
stubs accept.

The stubs are generated at build time by the locked grpcio-tools, and each one
checks the installed runtime when it is imported: a ``*_pb2_grpc`` module raises
``RuntimeError`` under a grpcio older than the one that generated it, and a
``*_pb2`` module refuses a protobuf older than its gencode version. A floor in
``coordinode/pyproject.toml`` below those versions lets an install resolve and
then fail the first time a client connects. These tests pin each floor to the
generated code that ships with it.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.version import Version

from coordinode._proto.coordinode.v1.query import cypher_pb2, cypher_pb2_grpc

_PYPROJECT = Path(__file__).resolve().parents[2] / "coordinode" / "pyproject.toml"


def _floor(package: str) -> Version:
    """The lower bound ``coordinode`` declares for ``package``."""
    dependencies = tomllib.loads(_PYPROJECT.read_text())["project"]["dependencies"]
    for line in dependencies:
        requirement = Requirement(line)
        if requirement.name == package:
            floors = [Version(spec.version) for spec in requirement.specifier if spec.operator in (">=", "==")]
            assert floors, f"{package} has no lower bound in {_PYPROJECT}"
            return max(floors)
    pytest.fail(f"{package} is not a dependency of coordinode")


def test_grpcio_floor_covers_the_generated_stubs() -> None:
    generated = Version(cypher_pb2_grpc.GRPC_GENERATED_VERSION)
    assert _floor("grpcio") >= generated, (
        f"coordinode allows grpcio {_floor('grpcio')}, but its stubs were generated by "
        f"grpcio-tools {generated} and refuse an older runtime at import"
    )


def test_protobuf_floor_covers_the_generated_messages() -> None:
    header = Path(cypher_pb2.__file__).read_text()
    match = re.search(r"^# Protobuf Python Version: (\S+)$", header, re.MULTILINE)
    assert match, "the generated module no longer records its protobuf gencode version"
    generated = Version(match.group(1))
    assert _floor("protobuf") >= generated, (
        f"coordinode allows protobuf {_floor('protobuf')}, but its messages were generated "
        f"for protobuf {generated} and refuse an older runtime at import"
    )
